config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'users#index'
  namespace :api do
    resources :users
  end

  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :user_name, presence: true
  validates :user_email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true
end

app/controllers/api/users_controller.rb
# frozen_string_literal: true

module Api
  class UsersController < ApplicationController
    def index
      users = User.all

      render json: users
    end

    def new
      user = User.new

      render json: user
    end

    def create
      user = User.new permitted_params

      user.save
      render json: user
    end

    def edit
      user = User.find(params[:id])

      render json: user
    end

    def update
      user = User.find(params[:id])

      user.update permitted_params
      render json: user
    end

    def destroy
      user = User.find(params[:id])
      user.destroy
      head :no_content, status: :ok
    end

    private

    def permitted_params
      params.require(:user).permit(:user_name, :user_email, :birthdate, :phone_number)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  def locals(locals)
    render locals: locals
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    users = User.all

    locals users: users
  end

  def new
    user = User.new

    locals user: user
  end

  def create
    user = User.new permitted_params

    if user.save
      redirect_to root_path
      flash[:success] = 'user created!'

    else
      flash[:danger] = 'creating error!'
      render :new, locals: { user: user }
    end
  end

  def edit
    user = User.find(params[:id])

    locals user: user
  end

  def update
    user = User.find(params[:id])

    if user.update permitted_params
      redirect_to root_path
      flash[:success] = 'user updated!'
    else
      flash[:danger] = 'updating error!'
      render :edit, locals: { user: user }
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
    flash[:success] = 'user deleted!'
  end

  private

  def permitted_params
    params.require(:user).permit(:user_name, :user_email, :birthdate, :phone_number)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_footer.html.haml
%footer.footer.mt-auto.py-3.bg-light
  .container
    %span.text-muted Alexey Leskov 2022

app/views/layouts/_header.html.haml
%body
  %header.p-3.bg-dark.text-white
    .container
      = link_to "ReactRails", root_path, id: "logo"
      .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
        %a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none{:href => "/"}
          %svg.bi.me-2{:height => "32", :width => "40"}
            %use{"xlink:href" => "#bootstrap"}
        %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        .text-end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ReactRails
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css", :integrity => "sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")

      = yield
      = render 'layouts/footer'

app/views/users/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_with model: user, local: true do |f|

      = f.label :name
      = f.text_field :user_name
      - user.errors.full_messages_for(:title).each do |message|
        %div= message

      = f.label :email
      = f.text_field :user_email
      - user.errors.full_messages_for(:text).each do |message|
        %div= message

      = f.label :phone
      = f.number_field :phone_number

      = f.label :birthdate
      = f.date_field :birthdate

      = f.submit "Submit", class: "btn btn-primary"

app/views/users/edit.html.haml
%html
%head
%body
%h1  Edit user
= render 'form', user: user

app/views/users/index.html.haml
= link_to "Create new user", new_user_path, class: "btn btn-primary"

%h1 Users List
%table
  %tr
    %th Id
    %th User Name
    %th Email
    %th Phone number
    %th Birthdate
  - users.each do |object|
    %tr
      %td= object.id
      %td= object.user_name
      %td= object.user_email
      %td= object.phone_number
      %td= object.birthdate
      %td= link_to "Edit", edit_user_path(object), class: "btn btn-primary"
      %td= button_to "Delete", user_path(object), method: :delete, class: "btn btn-primary"

app/views/users/new.html.haml
%html
%head
%body
%h1  Create user
= render 'form', user: user